pub(crate) const STREAM_MEASUREMENT: u32 = 0;
pub(crate) const STREAM_ACCESS_DELAY: u32 = 1;
pub(crate) const STREAM_ACCESS_NOISE: u32 = 2;
pub(crate) const STREAM_LABOR: u32 = 3;
pub(crate) const STREAM_POLICY: u32 = 4;
pub(crate) const STREAM_COALITION: u32 = 5;
pub(crate) const STREAM_REVISION: u32 = 6;
pub(crate) const STREAM_COMPETITOR: u32 = 7;
pub(crate) const STREAM_MONTHLY_EVENTS: u32 = 8;
pub(crate) const STREAM_ANNUAL_POLICY: u32 = 9;
// Reserve 100..=109 for per-system AI tie-break streams; logical streams stay below 10.
pub(crate) const STREAM_AI_PLAYER_BASE: u32 = 100;
